# Secret Scanning Configuration
# This file tells GitHub to exclude certain files from secret scanning

# Exclude files that may contain example tokens or test data
exclude:
  - "Tools/**/tokens.txt"
  - "Tools/**/proxies.txt"
  - "Tools/**/config.json"
  - "Tools/**/Generated.txt"
  - "Tools/**/hit.txt"
  - "generated_images/**"
  - "logs/**"
  - "*.log"
  - "*.bat"
  - "*.html"
  - "*.png"
  - "*.jpg"
  - "*.jpeg"

# Exclude patterns that look like tokens but are examples
patterns:
  - pattern: "MTAwMDAwMDAwMDAwMDAwMDAw\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+"
    description: "Example Discord token pattern"
    exclude: true 